M48
; DRILL file {KiCad (6.0.0)} date Mon Oct  9 13:49:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-09T13:49:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.5453Y-3.3984
X5.5453Y-3.4984
T2
X4.8619Y-3.3732
X5.0469Y-3.3732
T0
M30
